version: "3"

services:
  node-app:
    container_name: airchain_evm_tx_bot
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "${PORT:-31111}:31111"
    environment:
      NODE_ENV: development
        - .env
    command: /bin/sh -c "yarn && yarn start"
    restart: always
