version: "3"

services:
  node-app:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "${PORT:-3000}:3000"
    environment:
      NODE_ENV: development
        - .env
    command: /bin/sh -c "yarn && yarn start"
